"""
Dicionario de simplificacao dos nomes de ocupacao (Profissao) do painel IRPF.

Os nomes originais da Receita Federal (classificacao "Ocupacoes Principais") sao
frequentemente muito longos para caber em rotulos de grafico/tabela (ex.: "Analista
de sistemas, desenvolvedor de software, administrador de redes e bancos de dados e
outros especialistas em informatica (exceto tecnico)"). Este modulo mapeia o nome
original para uma versao curta usada apenas para EXIBICAO — o nome completo continua
disponivel (ex.: via tooltip/title) para quem precisar da descricao oficial exata.

Construido a partir das 132 ocupacoes distintas observadas nos dados do ES
(data/raw/irpf_municipio_profissao.csv). Ocupacoes que aparecerem em outras UFs e
ainda nao estiverem aqui caem no fallback (nome original, sem simplificacao) —
ver simplify().
"""

OCCUPATION_SHORT_NAMES = {
    "Outras ocupações não especificadas anteriormente": "Outras ocupações",
    "Dirigente, presidente e diretor de empresa industrial, comercial ou prestadora de serviços": "Dirigente de empresa",
    "Professor do ensino fundamental": "Professor (fundamental)",
    "Bancário, economiário, escriturário, secretário, assistente e auxiliar administrativo": "Bancário / auxiliar administrativo",
    "Outros trabalhadores de serviços diversos": "Trabalhador de serviços diversos",
    "Vendedor e prestador de serviços do comércio, ambulante, caixeiro-viajante e camelô": "Vendedor / comércio",
    "Gerente ou supervisor de empresa industrial, comercial ou prestadora de serviços": "Gerente / supervisor de empresa",
    "Motorista e condutor do transporte de passageiros (motorista de taxi, ônibus, pequena embarcação etc)": "Motorista de passageiros",
    "Outros técnicos de nível médio": "Técnico de nível médio",
    "Trabalhador de reparação e manutenção": "Reparação e manutenção",
    "Produtor na exploração agropecuária": "Produtor agropecuário",
    "Professor na educação infantil": "Professor (infantil)",
    "Engenheiro, arquiteto e afins": "Engenheiro / arquiteto",
    "Enfermeiro de nível superior, nutricionista, farmacêutico e afins": "Enfermeiro / farmacêutico",
    "Médico": "Médico",
    "Professor do ensino médio": "Professor (médio)",
    "Policial Militar": "Policial Militar",
    "Economista, administrador, contador, auditor e afins": "Economista / contador",
    "Servidor das demais carreiras da administração pública direta, autárquica e fundacional": "Servidor público (outras carreiras)",
    "Analista de sistemas, desenvolvedor de software, administrador de redes e bancos de dados e outros especialistas em informática (exceto técnico)": "Analista de sistemas / TI",
    "Técnico da ciência da saúde humana": "Técnico em saúde",
    "Advogado": "Advogado",
    "Trabalhador dos serviços de saúde": "Trabalhador da saúde",
    "Trabalhador da indústria extrativa e da construção civil": "Construção civil",
    "Trabalhador dos serviços de proteção e segurança (exceto militar)": "Segurança (civil)",
    "Odontólogo": "Dentista",
    "Pedagogo, orientador educacional": "Pedagogo",
    "Trabalhador de atendimento ao público, caixa, despachante, recenseador e afins": "Atendimento ao público",
    "Trabalhador de instalações siderúrgicas e de materiais de construção": "Siderurgia / materiais de construção",
    "Servidor das carreiras do  Poder Judiciário, Oficial de Justiça, Auxiliar, Assistente e Analista Judiciário": "Servidor do Judiciário",
    "Psicólogo": "Psicólogo",
    "Pescador, caçador e extrativista florestal": "Pescador / extrativista",
    "Professor do ensino superior": "Professor (superior)",
    "Delegado de Polícia e outros servidores das carreiras de polícia, exceto militar": "Delegado de Polícia",
    "Condutor e operador de robôs, veículos de equipamentos de movimentação de carga e afins": "Operador de máquinas / carga",
    "Trabalhador da transformação de metais e compósitos": "Transformação de metais",
    "Técnico em metalmecânica": "Técnico em metalmecânica",
    "Técnico das ciências administrativas e contábeis": "Técnico administrativo / contábil",
    "Outros técnicos de nível médio das ciências físicas, químicas, engenharia e afins": "Técnico em ciências / engenharia",
    "Trabalhador das indústrias química, petroquímica, borracha e plástico e afins": "Indústria química / plástico",
    "Fisioterapeuta": "Fisioterapeuta",
    "Assistente social e economista doméstico": "Assistente social",
    "Trabalhador da fabricação de alimentos, bebidas, fumo e de agroindústrias": "Indústria de alimentos",
    "Técnico em eletro-eletrônica e fotônica": "Técnico em eletrônica",
    "Trabalhador dos serviços de hotelaria e alimentação": "Hotelaria e alimentação",
    "Dirigente superior da administração pública (ocupante de cargo de direção, chefia, assessoria e de natureza especial), inclusive os das fundações públicas e autarquias": "Dirigente público superior",
    "Professor do ensino profissional": "Professor (profissionalizante)",
    "Trabalhador na  exploração agropecuária": "Trabalhador agropecuário",
    "Técnico em transportes (logística)": "Técnico em logística",
    "Profissional de marketing, de publicidade e de comercialização": "Marketing / publicidade",
    "Trabalhador dos serviços de administração, conservação e manutenção de edifícios": "Conservação de edifícios",
    "Sacerdote ou membro de ordens ou seitas religiosas": "Sacerdote / religioso",
    "Servidor das carreiras de auditoria fiscal e de fiscalização": "Auditor fiscal",
    "Bombeiro Militar": "Bombeiro Militar",
    "Técnico em informática": "Técnico em informática",
    "Técnico de laboratório, Raios-X e outros equipamentos e instrumentos de diagnóstico": "Técnico de laboratório",
    "Trabalhador dos serviços de embelezamento e cuidados pessoais": "Cuidados pessoais / estética",
    "Técnico em construção civil, de edificações e obras de infra-estrutura": "Técnico em construção civil",
    "Trabalhador de instalações e máquinas de fabricação de celulose e papel": "Indústria de celulose / papel",
    "Biólogo, biomédico e afins": "Biólogo / biomédico",
    "Instrutor e professor de escolas livres": "Instrutor (escolas livres)",
    "Gerente ou supervisor de empresa pública e sociedade de economia mista": "Gerente de empresa pública",
    "Agente e representante comercial, corretor, leiloeiro e afins": "Corretor / representante comercial",
    "Servidor das carreiras do Poder Legislativo": "Servidor do Legislativo",
    "Jornalista e repórter": "Jornalista",
    "Técnico de inspeção, fiscalização e coordenação administrativa": "Técnico de fiscalização",
    "Veterinário, patologista (veterinário) e zootecnista": "Veterinário / zootecnista",
    "Trabalhador das indústrias de madeira e do mobiliário": "Madeira e mobiliário",
    "Profissional da educação física (exceto professor)": "Educação física",
    "Operador de instalações de produção e distribuição de energia": "Operador de energia",
    "Desenhista industrial (designer), escultor, pintor artístico e afins": "Designer / artista plástico",
    "Militar da Marinha": "Militar da Marinha",
    "Trabalhador da fabricação e instalação eletro-eletrônica": "Fabricação eletro-eletrônica",
    "Trabalhador dos serviços domésticos em geral": "Serviços domésticos",
    "Operador de máquina agropecuária e florestal": "Operador de máquina agrícola",
    "Físico, químico, meteorologista, geólogo, oceanógrafo e afins": "Físico / químico / geólogo",
    "Técnico em navegação aérea, marítima, fluvial e metroferroviária": "Técnico em navegação",
    "Trabalhador das indústrias têxteis, do curtimento, do vestuário e das artes gráficas": "Têxtil / vestuário / gráfica",
    "Servidor das carreiras de gestão governamental, analista, gestor e técnico de planejamento": "Gestão governamental",
    "Advogado do setor público, Procurador da Fazenda, Consultor Jurídico, Procurador de autarquias e fundações públicas, Defensor Público": "Advogado / procurador público",
    "Servidor das carreiras do Ministério Público": "Servidor do Ministério Público",
    "Militar do Exército": "Militar do Exército",
    "Agrônomo e afins": "Agrônomo",
    "Fonoaudiólogo": "Fonoaudiólogo",
    "Membro do Poder Judiciário (Ministro, Juiz e Desembargador) e de Tribunal de Contas (Ministro e Conselheiro)": "Juiz / Desembargador",
    "Trabalhador de outras instalações agroindustriais": "Agroindústria (outras)",
    "Técnico em ciências físicas e químicas": "Técnico em física / química",
    "Bibliotecário, documentalista, arquivólogo, museólogo": "Bibliotecário / arquivólogo",
    "Cinegrafista, fotógrafo e outros técnicos em operação de máquinas de tratamento de dados": "Cinegrafista / fotógrafo",
    "Comissário de bordo, guia de turismo, agente de viagem e afins": "Turismo / comissário de bordo",
    "Membro do Poder Legislativo (Senador, Deputado Federal, Deputado Estadual e Vereador)": "Senador / Deputado / Vereador",
    "Joalheiro, vidreiro, ceramista e afins": "Joalheiro / ceramista",
    "Membro do Ministério Público (Procurador e Promotor)": "Procurador / Promotor",
    "Piloto de aeronaves, comandante de embarcações e oficiais de máquinas": "Piloto / comandante",
    "Matemático, estatístico, atuário e afins": "Matemático / estatístico",
    "Corretor e Administrador de Imóveis": "Corretor de imóveis",
    "Outros profissionais do espetáculo e das artes": "Profissional de espetáculo / artes",
    "Músico, arranjador, regente de orquestra ou coral": "Músico / regente",
    "Desenhista técnico e modelista": "Desenhista técnico",
    "Agente de Bolsa de Valores, câmbio e outros serviços financeiros": "Agente do mercado financeiro",
    "Presidente, diretor, gerente e supervisor de organismo internacional e de organização não-governamental": "Dirigente de ONG / organismo internac.",
    "Técnico da produção agropecuária": "Técnico agropecuário",
    "Técnico em operação de estações de rádio e televisão": "Técnico em rádio / TV",
    "Presidente e diretor de empresa pública e sociedade de economia mista": "Presidente de empresa pública",
    "Servidor das carreiras de ciência e tecnologia": "Servidor de ciência e tecnologia",
    "Dirigente ou administrador de partido político, organização patronal, sindical, filantrópica e religiosa": "Dirigente sindical / partidário",
    "Geógrafo": "Geógrafo",
    "Militar da Aeronáutica": "Militar da Aeronáutica",
    "Sociólogo e cientista político": "Sociólogo / cientista político",
    "Escritor, crítico, redator": "Escritor / redator",
    "Titular de Cartório": "Titular de Cartório",
    "Tradutor, intérprete, filólogo": "Tradutor / intérprete",
    "Atleta, desportista e afins": "Atleta",
    "Psicanalista": "Psicanalista",
    "Historiador": "Historiador",
    "Técnico em mineralogia e geologia": "Técnico em geologia",
    "Cenógrafo, decorador de interiores": "Cenógrafo / decorador",
    "Cantor e compositor": "Cantor / compositor",
    "Técnico em operação de aparelhos de sonorização, cenografia e projeção": "Técnico em sonorização",
    "Membro do Poder Executivo (Presidente da República, Vice-Presidente da República, Ministro de Estado, Governador, Vice-Governador, Prefeito, Vice-Prefeito": "Presidente / Governador / Prefeito",
    "Técnico de serviços culturais": "Técnico cultural",
    "Montador de aparelhos e instrumentos de precisão e musicais": "Montador de instrumentos",
    "Técnico em biologia": "Técnico em biologia",
    "Apresentador, artistas de artes populares e modelos": "Apresentador / modelo",
    "Ator, diretor de espetáculos": "Ator / diretor",
    "Locutor, comentarista": "Locutor / comentarista",
    "Técnico de bioquímica e da biotecnologia": "Técnico em biotecnologia",
    "Filósofo": "Filósofo",
    "Antropólogo e arqueólogo": "Antropólogo / arqueólogo",
    "Decorador e vitrinista": "Decorador / vitrinista",
    "Empresário e produtor de espetáculos": "Empresário de espetáculos",
    "Terapeuta Ocupacional": "Terapeuta ocupacional",
}


def simplify(nome_completo):
    """Retorna o nome curto se houver mapeamento; caso contrario, devolve o nome
    original sem alteracao (fallback seguro para ocupacoes ainda nao catalogadas,
    ex. de outras UFs)."""
    if nome_completo is None:
        return nome_completo
    return OCCUPATION_SHORT_NAMES.get(nome_completo, nome_completo)
